server:
  port: 8666

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 199629
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#  jpa:
#    show-sql: true




